smtp:
  host: smtp.mail.ru
  port: 465
  user: <user>
  password: <password>
  sender: <user>
  timeout: 5s
logger:
  need_debug: true
rabbitmq:
  url: amqp://guest:guest@localhost:5672/
  timeout: 5s
  exchange: emails
  exchange_type: direct
  queue: user_emails
  consumer_tag: pasteAPI-email-sender
